print("##################################################")
print("  ")
print(" # Author: Marcus Diego M. Gonzales")
print("  ")
print(" # Date: 26/01/2020 ")
print("  ")
print(" # Course: LBYCPA1 ")
print("  ")
print(" # My program is sort of a calculator. It will solve the equation, slope of a line. Also it can solve a Kinematic Equation. The user will only have to input the missing variable of the equation and the program would solve it on its own. ")